DROP TABLE IF EXISTS "Provider";
DROP TABLE IF EXISTS "Airline";
DROP TABLE IF EXISTS "SSchema";
DROP TABLE IF EXISTS "Account";
DROP TABLE IF EXISTS "ProviderAirline";
DROP TABLE IF EXISTS "ProviderSchema";